-- CREATING NEW DEPARTMENTS
insert into cc_ems.department_entity values 
(1,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PROJECT MANAGEMENT'),
(2,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'IT INFRASTRUCTURE AND OPERATIONS'),
(3,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'TECHNICAL SUPPORT'),
(4,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PRODUCT MANAGEMENT'),
(5,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'RESEARCH AND DEVELOPMENT'),
(6,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SALES AND MARKETING'),
(7,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'HUMAN RESOURCES'),
(8,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'FINANCE AND ADMINISTRATION'),
(9,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SOFTWARE DEVELOPMENT'),
(10,'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'LEGAL AND COMPLIANCE');

-- CREATING NEW JOB ROLES UNDER EACH DEPARTMENT
insert into cc_ems.job_role_entity values 
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PROJECT MANAGER',(select department_id from cc_ems.department_entity where department_name = 'PROJECT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SCRUM MASTER',(select department_id from cc_ems.department_entity where department_name = 'PROJECT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'BUSINESS ANALYST',(select department_id from cc_ems.department_entity where department_name = 'PROJECT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PRODUCT OWNER',(select department_id from cc_ems.department_entity where department_name = 'PROJECT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SYSTEM ADMINISTRATOR',(select department_id from cc_ems.department_entity where department_name = 'IT INFRASTRUCTURE AND OPERATIONS')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'NETWORK ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'IT INFRASTRUCTURE AND OPERATIONS')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'DATABASE ADMINISTRATOR',(select department_id from cc_ems.department_entity where department_name = 'IT INFRASTRUCTURE AND OPERATIONS')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'CLOUD ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'IT INFRASTRUCTURE AND OPERATIONS')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SECURITY ANALYST',(select department_id from cc_ems.department_entity where department_name = 'IT INFRASTRUCTURE AND OPERATIONS')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'HELP DESK TECHNICIAN',(select department_id from cc_ems.department_entity where department_name = 'TECHNICAL SUPPORT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'TECHNICAL SUPPORT SPECIALIST',(select department_id from cc_ems.department_entity where department_name = 'TECHNICAL SUPPORT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'CUSTOMER SUPPORT REPRESENTATIVE',(select department_id from cc_ems.department_entity where department_name = 'TECHNICAL SUPPORT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PRODUCT MANAGER',(select department_id from cc_ems.department_entity where department_name = 'PRODUCT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'PRODUCT MARKETING MANAGER',(select department_id from cc_ems.department_entity where department_name = 'PRODUCT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'UI/UX DESIGNER',(select department_id from cc_ems.department_entity where department_name = 'PRODUCT MANAGEMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'R&D ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'RESEARCH AND DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'DATA SCIENTIST',(select department_id from cc_ems.department_entity where department_name = 'RESEARCH AND DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'AI/ML ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'RESEARCH AND DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SALES MANAGER',(select department_id from cc_ems.department_entity where department_name = 'SALES AND MARKETING')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'ACCOUNT MANAGER',(select department_id from cc_ems.department_entity where department_name = 'SALES AND MARKETING')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'MARKETING SPECIALIST',(select department_id from cc_ems.department_entity where department_name = 'SALES AND MARKETING')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'DIGITAL MARKETING SPECIALIST',(select department_id from cc_ems.department_entity where department_name = 'SALES AND MARKETING')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'HR MANAGER',(select department_id from cc_ems.department_entity where department_name = 'HUMAN RESOURCES')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'RECRUITER',(select department_id from cc_ems.department_entity where department_name = 'HUMAN RESOURCES')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'TRAINING AND DEVELOPMENT SPECIALIST',(select department_id from cc_ems.department_entity where department_name = 'HUMAN RESOURCES')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'CHIEF FINANCIAL OFFICER',(select department_id from cc_ems.department_entity where department_name = 'FINANCE AND ADMINISTRATION')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'ACCOUNTANT',(select department_id from cc_ems.department_entity where department_name = 'FINANCE AND ADMINISTRATION')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'OFFICE MANAGER',(select department_id from cc_ems.department_entity where department_name = 'FINANCE AND ADMINISTRATION')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'SOFTWARE ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'FRONTEND DEVELOPER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'BACKEND DEVELOPER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'FULLSTACK DEVELOPER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'MOBILE DEVELOPER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'DEVOPS ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'QA ENGINEER',(select department_id from cc_ems.department_entity where department_name = 'SOFTWARE DEVELOPMENT')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'LEGAL COUNSELLER',(select department_id from cc_ems.department_entity where department_name = 'LEGAL AND COMPLIANCE')),
((select nextval('cc_ems.seq_jobrole_entity')),'superadmin',LOCALTIMESTAMP,'superadmin',LOCALTIMESTAMP,'COMPLIANCE OFFICER',(select department_id from cc_ems.department_entity where department_name = 'LEGAL AND COMPLIANCE'));